# -*- coding: utf-8 -*-
"""FInalstreamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2FqErDefnsv4ecDGOf3tnB50sIofhgV
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load the data
df = pd.read_csv("cps_project_data.csv")

# Create the education group column
def education_group(x):
    if 2 <= x <= 71:
        return "Less than High School"
    elif x == 73:
        return "High School"
    elif x == 81:
        return "Some College"
    elif x in [91, 92]:
        return "Associate Degree"
    elif x == 111:
        return "Bachelor's Degree"
    elif x in [123, 124, 125]:
        return "Graduate Degree"
    else:
        return "Unknown"

df["EDUC_GROUP"] = df["EDUC"].apply(education_group)

# Title
st.title("CPS Weekly Earnings Dashboard")

st.write(
    """
    This dashboard allows users to explore weekly earnings
    for workers based on education level.
    """
)

# Sidebar filter
education = st.sidebar.selectbox(
    "Select Education Group",
    sorted(df["EDUC_GROUP"].dropna().unique())
)

# Filter data
filtered = df[df["EDUC_GROUP"] == education]

# Display data
st.subheader("Filtered Data")
st.dataframe(filtered)

# Summary statistics
st.subheader("Summary Statistics")

st.write("Number of Workers:", len(filtered))
st.write("Mean Weekly Earnings:", round(filtered["EARNWEEK2"].mean(), 2))
st.write("Median Weekly Earnings:", round(filtered["EARNWEEK2"].median(), 2))
st.write("Standard Deviation:", round(filtered["EARNWEEK2"].std(), 2))

# Histogram
st.subheader("Distribution of Weekly Earnings")

fig, ax = plt.subplots()

ax.hist(
    filtered["EARNWEEK2"].dropna(),
    bins=20
)

ax.set_title("Distribution of Weekly Earnings")
ax.set_xlabel("Weekly Earnings")
ax.set_ylabel("Frequency")

st.pyplot(fig)